services:
  sparql-proxy:
    build:
      context: ../../src/sparql-proxy
      dockerfile: ../../sparql-proxy/common/Dockerfile
      args:
        ROOT_PATH: /${ENDPOINT_NAME:?}/
    image: sparql-proxy:${ENDPOINT_NAME:?}
    restart: always
    env_file: ../common/common.env
    environment:
      ROOT_PATH: /${ENDPOINT_NAME:?}/
      SPARQL_BACKEND: https://${BACKEND_HOST:-rdfportal.org}/backend/${ENDPOINT_NAME:?}/sparql
      QUERY_LOG_PATH: /app/logs/${ENDPOINT_NAME:?}.log
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
    volumes:
      - ${LOGS_DIR:?}:/app/logs
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
